---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[awscook::install]
      - recipe[awscook::mydeploy]
      - recipe[awscook::run_docker]
      - recipe[awscook::remove_containers]
    attributes:
